- symbol: '515790'
  name: 光伏ETF华泰柏瑞
  category: 行业
- symbol: '515050'
  name: 通信ETF华夏
  category: 行业
- symbol: '518850'
  name: 黄金ETF华夏
  category: 商品
- symbol: '159516'
  name: 半导体设备ETF国泰
  category: 行业
- symbol: '588200'
  name: 科创芯片ETF嘉实
  category: 行业
- symbol: '159326'
  name: 电网设备ETF华夏
  category: 行业
- symbol: '516020'
  name: 化工ETF华宝
  category: 行业
